SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM
    (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "%Intact%"
    ) S, ANIMAL_OUTS AS O
WHERE S.ANIMAL_ID = O.ANIMAL_ID
AND O.SEX_UPON_OUTCOME NOT LIKE "%Intact%"
